import Head from 'next/head';
import SearchPage from '@/pages/search/search';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main>
               <SearchPage/>
            </main>
        </>
    );
}
